### ISSUE TITLE
Error when close recipe window

### ISSUE THREAD

**Issue by GeekinaCave** [ElmarWueest/Recexplo#1]
if you right click in the item for close the recipe window when you have may of them (i assumed it work that way) this appears: 

Error while running event RecExplo::on_gui_elem_changed (ID 67)
__RecExplo__/lua/events.lua:125: attempt to index field 'elem_value' (a nil value)

**Comment by ElmarWueest** [comment]
should be fixed in new version 0.16.1

**Comment by GeekinaCave** [comment]
I tested the changes and it doesn't crash anymore, but then; how you do for delete recipes then you don't want to see anymore in the list?

**Comment by ElmarWueest** [comment]
Why do you want to be able to select no recipe?
Just close the window with ctrl+f. When you open it again, the same item is selected then before.

**Comment by GeekinaCave** [comment]
Sorry, i probably didn't explain myself: the problem is none of the item you select for search recipes eventually can be remove; so as the game progress you gonna be cluttered with a list of items then you don't need to know the recipe anymore (like when you advance in technology in bobs-angels).

one suggestion of the mod mechanics could be:

![description01](https://user-images.githubusercontent.com/8534866/34456969-e89ed456-ed71-11e7-80ce-4bb6da71e93d.png)

INITIAL STATE: when you use the mod for first time since there's no item selected; it prompts the window for selecting the item you want to search (same window when you click in 1.).

MIDDLE STATE: as the game progress if you want to remove an item from the search list you cant do it by right click on it (1.).

FINAL STATE: if you have one item only in the list; if you right click over it closes the window returning to INITIAL STATE.

I wish to have the skill in Lua for make the changes myself and submit a push of it.

Don't get me wrong: your mod exceed in practicability to "Factorio NEI" and "What is really used for?" combined, I'm just trying to help to improve it.

**Comment by ElmarWueest** [comment]
First, thank you for your feedback. Positive feedback is always good ;-)
Second, when I understand you right: you wish to be able to delete Items from the history?
Am I right? When yes, then it's absolutely feasible.

**Comment by GeekinaCave** [comment]
Yes, thats the idea 👍.
