### ISSUE TITLE
[0.16.9] Crash still present regarding certain items not having inputs on recipe calculator

### ISSUE THREAD

**Issue by jarquafelmu** [ElmarWueest/Recexplo#11]
### Description

Game crash when opening some items in the recipe calculator and they're not generating the input section of the calculator. This happens with some modded items and some vanilla items. This seems to be affecting a lot of modded items from Bob's and from Pyrandon's mods but the issue is not exclusive to mods. It also affects some vanilla items.

Items tested which showed this error
- Steel Axe
- Yellow Underground belt
- Chromium-Cobalt Alloy

Screenshot:
https://imgur.com/a/jBhd2JK

---------------------------------------------------
### Error
```
Error while running event RecExplo::on_gui_click (ID 1)
__RecExplo__/lua/recipe_cal.lua:429: attempt to index field 'input_cal_recipe_frame' (a nil value)
```
---------------------------------------------------
### Reproduction

1. Open recipe explorer
1. Select one of the items from above 
1. Open Recipe Calculator
1. Click record
1. Add the product to the recipe calculator
1. Product will not have an input section
1. Change the product factory or the output factory
1. Crash
---------------------------------------------------
### Versions
Factorio 0.16.51
Recexplo 0.16.9

**Comment by ElmarWueest** [comment]
Many thanks jarquafelmu for your very detailed bug descriptions. Those help a lot.
is fixed in 0.16.10
