### ISSUE TITLE
gui_click_error

### ISSUE THREAD

**Issue by Firemonkey08** [ElmarWueest/Recexplo#12]
Get this error, when i click on a product or ingredient icon:
on_gui_click(ID 1)
RecExplo/lua/recipe_cal.lua:391: attempt to perform arithmeticon field 'crafting speed' (a nil value)

**Comment by ElmarWueest** [comment]
Hello
I'm back from my holidays.
please provide more information.
I need on minimum following information:
-mod version
-game version
-an instructions to reproduce the bug

without those information it is very difficult to fix the bug you have found.

**Comment by jarquafelmu** [comment]
Running mod version 0.16.10 and game version 0.16.51, I am unable to reproduce this bug. Firemonkey please let Elmar know which items and which versions cause this issue for you so that it can be resolved.

**Comment by Firemonkey08** [comment]
It´s fixed in 0.16.11. Thanks.
