### ISSUE TITLE
[0.16.10] Issue: Recipe calculator spams the chat

### ISSUE THREAD

**Issue by jarquafelmu** [ElmarWueest/Recexplo#13]
### Description

This is not a bug per-say, but when adding a new item to the recipe calculator, the mod spams the chat with `draw begin io`

---------------------------------------------------
### Screenshots

[https://imgur.com/a/YZLXEX0](https://imgur.com/a/YZLXEX0)

---------------------------------------------------
### Reproduction

1. Click record in recipe calculator
1. Click on an item
1. `draw being io` is sent to the chat.
 
---------------------------------------------------
### Versions
Factorio 0.16.51
Recexplo 0.16.10

**Comment by ElmarWueest** [comment]
sorry
this is a debug information I forgot to remove.
is removed in version 0.16.11
