### ISSUE TITLE
[0.16.10] Bug: Not all items generate an input or output section in recipe calculator

### ISSUE THREAD

**Issue by jarquafelmu** [ElmarWueest/Recexplo#14]
### Description
Some recipes from Bio Industries don't generate an input or output section in the recipe explorer. This no longer causes crashing but it makes it difficult if you want to test throughput that that one item alone. This issue could be present for other items and other mods but bio industries was one that generated it reliably.

Items tested which showed this issue
 - Raw Wood (Bio industries recipe: 20 seedling + 100 water = 40 raw wood + 80 wood pulp
 - Seedling (Bio Industries)

---------------------------------------------------
### Screenshots

[https://imgur.com/a/w7q0T1T](https://imgur.com/a/w7q0T1T)

---------------------------------------------------
### Reproduction

1. Start with empty recipe calculator
1. click record
1. click on raw wood in product for the bio industry recipe
1. no input generated.

Repeat for seedling and no output will be generated. In order to get in an input and output you must have seeds -> seedling -> raw wood in the recipe calculator
 
---------------------------------------------------
### Versions
Factorio 0.16.51
Recexplo 0.16.10
Bio Industries 2.6.11

**Comment by ElmarWueest** [comment]
This is not a bug, this is a feature. ;-)
When a recipe has multiple ingredients or products and you don't select one, then the calculator is unable to solve the product chain. In this situation there will be no output or input window.

solution:
Click on the "add to history" button on the recipe and select an ingredient or product accordently.

Thank you for your bug report**s**.
Do you have any suggestions for some optimisation or additional feature. Let me know it.
