### ISSUE TITLE
Crash when viewing items that no longer exists

### ISSUE THREAD

**Issue by Nyhmus** [ElmarWueest/Recexplo#17]
We play with mods and removed a mod and still hat recipes of them opened.
Game crashed when we tried to open the explorer or clicked on any of them still in the history list.

261.927 Error MainLoop.cpp:1035: Exception at tick 2759541: Error while running event RecExplo::on_gui_click (ID 1)
__RecExplo__/lua/explo_gui.lua:158: attempt to index field '?' (a nil value)
261.927 Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running event RecExplo::on_gui_click (ID 1)
__RecExplo__/lua/explo_gui.lua:158: attempt to index field '?' (a nil value)"

**Comment by ElmarWueest** [comment]
is fixed in the upcoming version 0.16.13
