### ISSUE TITLE
Factorio .17 name conventions update - player now character

### ISSUE THREAD

**Issue by aoakeley** [ElmarWueest/Recexplo#23]
Update notes: "Renamed the character entity type and name from "player" to "character" to make it consistent with how we call/access it in all other places."

Errror:
The mod Recipe Explorer caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecExplo::on_player_main_inventory_changed (ID 32)
real number expected got nil.
stack traceback:
RecExplo/lua/events.lua:433: in function <RecExplo/lua/events.lua:429>
stack traceback:
[C]: in function 'get_inventory'
RecExplo/lua/events.lua:433: in function <RecExplo/lua/events.lua:429>

I'm using version RecExplo 0.17.01

**Comment by ElmarWueest** [comment]
fixed on 0.17.02
