### ISSUE TITLE
Bugs in the use of mod

### ISSUE THREAD

**Issue by TOYBOXSM** [ElmarWueest/Recexplo#26]
Error while running event RecExplo::on_configuration_changed
__RecExplo__/lua/events.lua:610: attempt to index field '?' (a nil value)
stack traceback:
	__RecExplo__/lua/events.lua:610: in function <__RecExplo__/lua/events.lua:605>

**Comment by TOYBOXSM** [comment]
factorio 0.17.79 mod 0.17.5

**Comment by ElmarWueest** [comment]
should be fixed in new version please update.
