### ISSUE TITLE
"Past Recipe" Item on Cursor

### ISSUE THREAD

**Issue by Lezreth** [ElmarWueest/Recexplo#6]
When viewing recipes, if you click on the icon for a recipe, an item is placed on the cursor that says "past recipe".  For example, select Underground belt, it shows the recipe for it, and where it says "Underground belt: " followed by the icon for it, clicking on that icon will place the "past recipe" on the cursor.  This also happens with all recipes viewed with the "find where it's used" option.

**Comment by ElmarWueest** [comment]
This isn't a bug this is a feature ;-)
When you have clicked on a recipe icon you get a "past recipe" (should be "past**e** recipe") item on the cursor, as you discovered. With this item you can select en area. In this area all crafting machines will now producing your selected recipe.

**Comment by ElmarWueest** [comment]
fixed
