### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by Lezreth** [ElmarWueest/Recexplo#7]
The game is crashing with the following error message:

26.335 Error MainLoop.cpp:1030: Exception at tick 440: Error while running event RecExplo::on_gui_checked_state_changed (ID 3)
Gui element with name recexplo_technology_dirty-mining already present in the parent element.

stack traceback:
`

	__RecExplo__/lua/explo_gui.lua:626: in function 'draw_required_technologies'
	__RecExplo__/lua/explo_gui.lua:435: in function 'draw_recipe'
	__RecExplo__/lua/explo_gui.lua:335: in function 'create_all_where_used'
	__RecExplo__/lua/explo_gui.lua:321: in function 'create_all_where_used_container'
	__RecExplo__/lua/explo_gui.lua:248: in function 'create_results'
	__RecExplo__/lua/explo_gui.lua:238: in function 'update_results'
	__RecExplo__/lua/explo_gui.lua:51: in function 'update'
	__RecExplo__/lua/events.lua:172: in function <__RecExplo__/lua/events.lua:158
`
The following mods are required to replicate this error:
- Creative Mode (Fix for 0.16)
- DirtyMining
- Recipe Explorer

The following steps will replicate the error:
- Play > New Game > Generate (The settings chosen do not matter)
- Press Tab to acknowledge freeplay message
- The "Enable Creative Mode?" message displays, selecting any of the buttons is not required
- Press Ctrl+F to bring up the Recipe Explorer
- Select water
- Click on "find where it's used"

**Comment by ElmarWueest** [comment]
sorry for the late response

i'm working at the moment on a bigger update and will try to fix it with thise update.
At the first lock, it seems like there are 2 technologies with the same internal name, but this is not possible on my knowledge.
I will try to reproduce the bug.
Thank you for your feedback

**Comment by ElmarWueest** [comment]
fixed in 0.16.7 coming soon
