### ISSUE TITLE
[Crash] Items without inputs cause the game to crash when changing factories.

### ISSUE THREAD

**Issue by jarquafelmu** [ElmarWueest/Recexplo#8]
I am using both Pymods and Bob's mods but I'm not sure if they are the cause. Some items in the recipe calculator come up as not having an input section.

For those items, changing the factory on the item construction section or the output section cause the game to crash with the following error code:
`Error MainLoop.cpp:1035: Exception at tick 27045225: Error while running event RecExplo::on_gui_click (ID 1)
__RecExplo__/lua/recipe_cal.lua:429: attempt to index field 'input_cal_recipe_frame' (a nil value)`

**Comment by ElmarWueest** [comment]
yes this is a bug on my side.
will fix it with 0.16.7 comming next weekend.

**Comment by ElmarWueest** [comment]
should be fixed with 0.16.7
